### ISSUE TITLE
localhost:9000 redirects to localhost:9443

### ISSUE THREAD

**Issue by piercelamb** [Enalmada/play-https-redirect#2]
I think this is expected behavior, but how do you continue to test changes locally now? I just get a "site cannot be reached" at that URL. Even after commenting out the redirect code it continues to do it.

**Comment by piercelamb** [comment]
For those finding this later, you need to pass the following commands when you run activator:

activator run -Dhttp.port=disabled -Dhttps.port=9443

**Comment by Enalmada** [comment]
Yes, beat me to it!  You do need to make sure it is turned on:
https://www.playframework.com/documentation/2.7.x/ConfiguringHttps
